### PR TITLE
Fix: make caighdean MT provider protocol agnostic

### LINKED ISSUE #4600: Caighdean Gaelic Machine Translation provider uses http only and breaks on https sites
The Caighdean MT engine is hardcoded to use http.  This works on http Pootle sites.  But on on https sites.

Solutions:
1. Get Caighdean onto https - that will make it work for Pootle on https or http
2. Disable the checker if Pootle is running on http

### PR DESCRIPTION
**Pull request by phlax**
fixes #4600

### CODE REVIEW

**Comment by julen** [comment]
From Paul Irish's blog, on the topic of [protocol relative URLs](http://www.paulirish.com/2010/the-protocol-relative-url/):
> Now that SSL is encouraged for everyone and doesn’t have performance concerns, this technique is now an anti-pattern. If the asset you need is available on SSL, then always use the https:// asset.
>
> Allowing the snippet to request over HTTP opens the door for attacks like the recent Github Man-on-the-side attack. It’s always safe to request HTTPS assets even if your site is on HTTP, however the reverse is not true.

**Comment by phlax** [comment]
@julen fair point, ill update

File: pootle/static/js/editor/mt/providers/CaighdeanTranslate.js [hunk 1]
```diff
@@ -16,7 +16,7 @@ class CaighdeanTranslate extends MTProvider {
       apiKey,
       name: 'caighdean-translate',
       displayName: 'Caighdeán Translate',
-      url: 'http://borel.slu.edu/cgi-bin/seirbhis3.cgi',
+      url: '//borel.slu.edu/cgi-bin/seirbhis3.cgi',
       supportedLanguages: ['gd', 'gv', 'ga_IE', 'ga-IE'],
```
Comment (dwaynebailey) [inline pootle/static/js/editor/mt/providers/CaighdeanTranslate.js]: Can we add pure 'ga' here also please

Comment (phlax) [inline pootle/static/js/editor/mt/providers/CaighdeanTranslate.js]: im not sure if it would need to be recognised by the MT server - @kscanne does the server support plain `ga` ?

Comment (unho) [inline pootle/static/js/editor/mt/providers/CaighdeanTranslate.js]: It does. But in `foinse` you can now only specify `gd` or `gv` for now.

Comment (unho) [inline pootle/static/js/editor/mt/providers/CaighdeanTranslate.js]: Also right now this MT doesn't require specifying the target language since it always assumes `ga`, so my guess is that `ga` (or equivalent) is only necessary in `supportedLanguages` to enable this MT button on the translation editor UI.

Comment (phlax) [inline pootle/static/js/editor/mt/providers/CaighdeanTranslate.js]: cool, ill add
