### PR TITLE
Set sidebar width when measuring height

### LINKED ISSUE #3969: Sidebar gets wrong height when hidden on page load
to reproduce:

- put a lot of content in the sidebar
- load a page with the sidebar closed
- expand the sidebar and witness that the sidebar is ~2x the height of the contained elements

this is fixed by #3963 and is related to #3812

### PR DESCRIPTION
**Pull request by phlax**
When taking a measurement of the hidden sidebar, it needs to have the correct width

touch #3812

fixes #3969

### CODE REVIEW

File: pootle/static/js/helpers.js [hunk 1]
```diff
@@ -37,10 +37,13 @@ var helpers = {
         bodyPadding = parseInt($body.css('padding-bottom'), 10),
         contentAreaHeight = $('#wrapper').height() - $body.offset().top -
                             bodyPadding,
-        sidebarHeight = $('#sidebar #sidebar-content').height() +
-                        $('#footer').height() + bodyPadding,
-        newHeight = Math.max(contentAreaHeight, sidebarHeight);
+        sidebarHeight, newHeight;
 
+    $('#sidebar').css("width", "30%");
```
Comment (unho) [inline pootle/static/js/helpers.js]: Can you explain why do you set this width and not other?

**Comment by unho** [comment]
Just tested and this seems not to be fixing #3812.

**Comment by julen** [comment]
Could you elaborate on how this affects height and therefore why is it necessary? I see no correlation between both http://jsfiddle.net/27dbcxpk/1/

**Comment by phlax** [comment]
If you load a page *with the sidebar closed* and *a lot of content in sidebar* the measurement taken for the height of the sidebar is wrong (tested iceweasel 39.0, chromium 44.0.2403.89). This is due to the #sidebar-content element being squashed widthways when hidden, and therefore having more height.

so to be clear this is *not* #3812 - its almost the opposite.

to reproduce:
- put a lot of content in the sidebar
- load a page with the sidebar closed
- expand the sidebar and witness that the sidebar is ~2x the height of the contained elements

When the sidebar is expanded it uses 30% of viewport. As #sidebar has "layout" setting the contained elements width to a % will use a %  of the parent element not the viewports - @unho this is why the width is temporarily set on #sidebar and not #sidebar-content

@julen your jsfiddle example does not have hidden elements with layout and contained elements - so im not sure its that relevant.

Re: #3812 - i havent been able to reproduce and have had difficulty getting access to linode and the referenced page. I am going to try to resolve this now

**Comment by unho** [comment]
> so to be clear this is not #3812 - its almost the opposite.

Let me suggest you to create an issue for the bug this PR is trying to fix and reference only to that new issue instead of unrelated #3812. Thanks!

**Comment by phlax** [comment]
As suggested i have put the problem that this addresses into a separate ticket - #3969

**Comment by julen** [comment]
@phlax this is basically the same code as the sidebar http://jsfiddle.net/27dbcxpk/3/

**Comment by phlax** [comment]
@julen im struggling to reproduce as a jsfiddle.

Could you please try to reproduce bug #3969

File: pootle/static/js/helpers.js (hunk 1 above)
Comment (julen) [inline pootle/static/js/helpers.js]: It's [the width of the sidebar](https://github.com/translate/pootle/blob/a328894179ff7c7a4ae6f88bf15087f979590865/pootle/static/css/style.css#L531) when it's open.
